// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJaaOicOSlYx6EYcT90aa67e1UMw5-1Xs',
    appId: '1:861562404632:web:1d4d26f8e2301b93f0e86d',
    messagingSenderId: '861562404632',
    projectId: 'ovzr-6ef55',
    authDomain: 'ovzr-6ef55.firebaseapp.com',
    storageBucket: 'ovzr-6ef55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1wsbOHenFnti0mT8vP8YV6aFWfd7iyJE',
    appId: '1:861562404632:android:42eb0f60bfb64c2af0e86d',
    messagingSenderId: '861562404632',
    projectId: 'ovzr-6ef55',
    storageBucket: 'ovzr-6ef55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKl-7vOc9M0_ls1hZyoVl280cgdnyXhU',
    appId: '1:861562404632:ios:5ed7afc238e52f50f0e86d',
    messagingSenderId: '861562404632',
    projectId: 'ovzr-6ef55',
    storageBucket: 'ovzr-6ef55.appspot.com',
    iosBundleId: 'com.example.ovzr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwKl-7vOc9M0_ls1hZyoVl280cgdnyXhU',
    appId: '1:861562404632:ios:5ed7afc238e52f50f0e86d',
    messagingSenderId: '861562404632',
    projectId: 'ovzr-6ef55',
    storageBucket: 'ovzr-6ef55.appspot.com',
    iosBundleId: 'com.example.ovzr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJaaOicOSlYx6EYcT90aa67e1UMw5-1Xs',
    appId: '1:861562404632:web:c5223df85d4c60f1f0e86d',
    messagingSenderId: '861562404632',
    projectId: 'ovzr-6ef55',
    authDomain: 'ovzr-6ef55.firebaseapp.com',
    storageBucket: 'ovzr-6ef55.appspot.com',
  );
}
